---
apiVersion: v1
kind: Service                    
metadata:
  name: go-k8s  
spec:
  type: NodePort                 
  ports:                         
  - name: http
    port: 4040
    targetPort: 4040
  selector:
    app: go-k8s         