---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: go-k8s                  
spec:
  replicas: 3                    
  selector:
    matchLabels:
      app: go-k8s         
  template:                      
    metadata:
      labels:                    
        app: go-k8s  
    spec:                        
      containers:
      - name: go-k8s
        image: monojit2012/go-k8s:2.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 4040
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:          
          httpGet:
            path: /health
            port: 4040
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          
          httpGet:
            path: /readiness
            port: 4040
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
            
        volumeMounts:
          - mountPath: /log
            name: log-volume
      volumes:
        - name: log-volume
          emptyDir: {}    
            